### ISSUE TITLE
Critical tokens

### ISSUE THREAD

**Issue by hbrachemi** [SeekingDream/NMTSloth#1]
Hello,
You mentioned in your attack that you determine critical tokens before optimizing the adversarial sentence but I can't seem to find the piece of code that does that, could u please precise which file I should refer to and is there a way that method works on GPT architectures? 
Thanks in advance

**Comment by Cap-Ning** [comment]
> Hello, You mentioned in your attack that you determine critical tokens before optimizing the adversarial sentence but I can't seem to find the piece of code that does that, could u please precise which file I should refer to and is there a way that method works on GPT architectures? Thanks in advance

Thank you for your interest! In this paper, we designed a loss function to finding critical tokens, corresponding to lines 197 to 202 in FSE22_NMTSloth/src/base_attack.py, with the implementation of three mutation methods behind line 203. Additionally, in our latest work accepted by TOSEM, we propose a black-box key token searching method and extend the study from NMT to LLM (including the GPT series). You can find more details in our latest paper: ([https://dl.acm.org/doi/10.1145/3664812](https://dl.acm.org/doi/10.1145/3664812))

**Comment by hbrachemi** [comment]
Thank you, 

it seems that the method loss is not implemented within the class though, is it the CE loss computed between a one hot encoded vector and the probability vector of each token ?

Thank you for the reference, I will refer to the paper for further adaptations of my approach

**Comment by SeekingDream** [comment]
The method loss is implemented in the `compute_loss` functions in each class, which can be found in this [file](https://github.com/SeekingDream/FSE22_NMTSloth/blob/main/src/my_attack.py).
