### ISSUE TITLE
pip install version issues

### ISSUE THREAD

**Issue by Jiadwu2** [SeekingDream/NMTSloth#2]
Hi, I am trying to run LLMEffichecker, and there are several lines in **requirement.txt** that do not have specific versions such as:

decorator @ file:///home/ktietz/src/ci/decorator_1611930055503/work
networkx @ file:///tmp/build/80754af9/networkx_1598376031484/work
nvidia-pyprof @ file:///home/sxc180080/PyProf

I can't configure the environment rightly.

**Comment by SeekingDream** [comment]
Thanks for your interests in our work.

I think these libs are not necessary, try to delete these libs and run it again.
